services:
  - type: web
    name: practia-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PRACTIA_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
    autoDeploy: true
    healthCheckPath: /health
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"